if (isDedicated) exitWith {};

_dude = _this select 0;
_Uitems = uniformItems _dude;
_uniform = selectrandom [
"arg_shirt_checked_grey_uniform",
"arg_shirt_checked_green_uniform",
"arg_shirt_checked_bluegreen_texture_uniform",
"arg_shirt_checked_blue_uniform",
"arg_shirt_checked_pink_uniform",
"arg_shirt_checked_purple_uniform",
"arg_shirt_checked_red_uniform",
"arg_shirt_checked_tartan_uniform",
"arg_shirt_checked_yellow_01_texture_uniform",
"arg_shirt_blue_gold_watch_uniform",
"arg_shirt_green_gold_watch_uniform",
"arg_shirt_ice_grey_gold_watch_uniform",
"arg_shirt_olive_gold_watch_uniform",
"arg_shirt_orange_gold_watch_uniform",
"arg_shirt_white_gold_watch_uniform",
"arg_shirt_yellow_gold_watch_uniform",
"U_C_Mechanic_01_F",
"rds_uniform_Worker2",
"rds_uniform_Worker1",
"rds_uniform_Woodlander1",
"rds_uniform_schoolteacher",
"rds_uniform_Rocker4",
"rds_uniform_Rocker3",
"rds_uniform_Rocker2",
"rds_uniform_Rocker1",
"rds_uniform_Profiteer1",
"rds_uniform_Profiteer2",
"rds_uniform_Profiteer3",
"rds_uniform_Profiteer4",
"rds_uniform_Functionary1",
"rds_uniform_Functionary2",
"rds_uniform_citizen1",
"rds_uniform_citizen2",
"rds_uniform_citizen3",
"rds_uniform_citizen4",
"rds_uniform_Rocker4",
"rds_uniform_Rocker3",
"rds_uniform_Rocker2",
"rds_uniform_Rocker1",
"gm_gc_civ_uniform_man_01_80_blu",
"gm_gc_civ_uniform_man_01_80_gry",
"gm_gc_civ_uniform_man_01_80_brn",
"gm_gc_civ_uniform_man_01_80_blk",
"gm_gc_civ_uniform_man_01_80_blu",
"gm_gc_civ_uniform_man_01_80_gry",
"gm_gc_civ_uniform_man_01_80_brn",
"gm_gc_civ_uniform_man_01_80_blk",
"gm_gc_civ_uniform_man_01_80_blu",
"gm_gc_civ_uniform_man_01_80_gry",
"gm_gc_civ_uniform_man_01_80_brn",
"gm_gc_civ_uniform_man_01_80_blk",
"U_I_L_Uniform_01_tshirt_black_F",
"U_I_L_Uniform_01_tshirt_skull_F",
"U_I_L_Uniform_01_tshirt_sport_F",
"U_C_Uniform_Farmer_01_F",
"U_C_E_LooterJacket_01_F",
"U_C_Man_casual_1_F",
"U_C_Man_casual_3_F",
"U_C_Man_casual_2_F",
"U_I_C_Soldier_Bandit_1_F",
"U_I_C_Soldier_Bandit_2_F",
"U_I_C_Soldier_Bandit_3_F",
"U_I_C_Soldier_Bandit_4_F",
"U_I_C_Soldier_Bandit_5_F",
"U_Rangemaster",
"U_Marshal",
"U_Marshal",
"U_Marshal",
"U_Marshal",
"U_Marshal",
"U_Marshal",
"U_Marshal",
"U_Marshal",
"U_C_HunterBody_grn",
"U_C_HunterBody_grn",
"U_C_HunterBody_grn",
"U_C_HunterBody_grn",
"U_BG_Guerilla3_1",
"U_BG_Guerilla3_1",
"U_BG_Guerilla3_1",
"U_BG_Guerilla3_1",
"U_BG_Guerilla2_2",
"U_BG_Guerilla2_2",
"U_BG_Guerilla2_3",
"U_BG_Guerilla2_3",
"U_BG_Guerilla2_1",
"U_BG_Guerilla2_1",
"U_C_Poor_1"
];








_dude forceadduniform _uniform;
{_dude addItemToUniform _x} forEach _Uitems;