bon_recruit_recruitableunits = ["oksv_hmg_gorka",
"oksv_secnumber_gorka",
"oksv_marksman_gorka",
"oksv_marksman_panama_gorka",
"oksv_medic_gorka",
"oksv_rifleman_gorka",
"oksv_rifleman_rpg_gorka",
"oksv_rto_gorka",
"oksv_serg_gorka",
"oksv_hmg_klmk",
"oksv_secnumber_klmk",
"oksv_marksman_klmk",
"oksv_marksman_panama_klmk",
"oksv_medic_klmk",
"oksv_rifleman_klmk",
"oksv_rifleman_rpg_klmk",
"oksv_rto_klmk",
"oksv_serg_klmk"];